//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace Tungnt.NET.WP8._1Silverlight.WCFDemo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFDemo.IWCFRestDemo")]
    public interface IWCFRestDemo {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWCFRestDemo/GetMessage", ReplyAction="http://tempuri.org/IWCFRestDemo/GetMessageResponse")]
        System.IAsyncResult BeginGetMessage(System.AsyncCallback callback, object asyncState);
        
        string EndGetMessage(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWCFRestDemo/PostMessage", ReplyAction="http://tempuri.org/IWCFRestDemo/PostMessageResponse")]
        System.IAsyncResult BeginPostMessage(string userName, System.AsyncCallback callback, object asyncState);
        
        string EndPostMessage(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFRestDemoChannel : Tungnt.NET.WP8._1Silverlight.WCFDemo.IWCFRestDemo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PostMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFRestDemoClient : System.ServiceModel.ClientBase<Tungnt.NET.WP8._1Silverlight.WCFDemo.IWCFRestDemo>, Tungnt.NET.WP8._1Silverlight.WCFDemo.IWCFRestDemo {
        
        private BeginOperationDelegate onBeginGetMessageDelegate;
        
        private EndOperationDelegate onEndGetMessageDelegate;
        
        private System.Threading.SendOrPostCallback onGetMessageCompletedDelegate;
        
        private BeginOperationDelegate onBeginPostMessageDelegate;
        
        private EndOperationDelegate onEndPostMessageDelegate;
        
        private System.Threading.SendOrPostCallback onPostMessageCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WCFRestDemoClient() {
        }
        
        public WCFRestDemoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFRestDemoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFRestDemoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFRestDemoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetMessageCompletedEventArgs> GetMessageCompleted;
        
        public event System.EventHandler<PostMessageCompletedEventArgs> PostMessageCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Tungnt.NET.WP8._1Silverlight.WCFDemo.IWCFRestDemo.BeginGetMessage(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMessage(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string Tungnt.NET.WP8._1Silverlight.WCFDemo.IWCFRestDemo.EndGetMessage(System.IAsyncResult result) {
            return base.Channel.EndGetMessage(result);
        }
        
        private System.IAsyncResult OnBeginGetMessage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Tungnt.NET.WP8._1Silverlight.WCFDemo.IWCFRestDemo)(this)).BeginGetMessage(callback, asyncState);
        }
        
        private object[] OnEndGetMessage(System.IAsyncResult result) {
            string retVal = ((Tungnt.NET.WP8._1Silverlight.WCFDemo.IWCFRestDemo)(this)).EndGetMessage(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMessageCompleted(object state) {
            if ((this.GetMessageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMessageCompleted(this, new GetMessageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMessageAsync() {
            this.GetMessageAsync(null);
        }
        
        public void GetMessageAsync(object userState) {
            if ((this.onBeginGetMessageDelegate == null)) {
                this.onBeginGetMessageDelegate = new BeginOperationDelegate(this.OnBeginGetMessage);
            }
            if ((this.onEndGetMessageDelegate == null)) {
                this.onEndGetMessageDelegate = new EndOperationDelegate(this.OnEndGetMessage);
            }
            if ((this.onGetMessageCompletedDelegate == null)) {
                this.onGetMessageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMessageCompleted);
            }
            base.InvokeAsync(this.onBeginGetMessageDelegate, null, this.onEndGetMessageDelegate, this.onGetMessageCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Tungnt.NET.WP8._1Silverlight.WCFDemo.IWCFRestDemo.BeginPostMessage(string userName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPostMessage(userName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string Tungnt.NET.WP8._1Silverlight.WCFDemo.IWCFRestDemo.EndPostMessage(System.IAsyncResult result) {
            return base.Channel.EndPostMessage(result);
        }
        
        private System.IAsyncResult OnBeginPostMessage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userName = ((string)(inValues[0]));
            return ((Tungnt.NET.WP8._1Silverlight.WCFDemo.IWCFRestDemo)(this)).BeginPostMessage(userName, callback, asyncState);
        }
        
        private object[] OnEndPostMessage(System.IAsyncResult result) {
            string retVal = ((Tungnt.NET.WP8._1Silverlight.WCFDemo.IWCFRestDemo)(this)).EndPostMessage(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPostMessageCompleted(object state) {
            if ((this.PostMessageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PostMessageCompleted(this, new PostMessageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PostMessageAsync(string userName) {
            this.PostMessageAsync(userName, null);
        }
        
        public void PostMessageAsync(string userName, object userState) {
            if ((this.onBeginPostMessageDelegate == null)) {
                this.onBeginPostMessageDelegate = new BeginOperationDelegate(this.OnBeginPostMessage);
            }
            if ((this.onEndPostMessageDelegate == null)) {
                this.onEndPostMessageDelegate = new EndOperationDelegate(this.OnEndPostMessage);
            }
            if ((this.onPostMessageCompletedDelegate == null)) {
                this.onPostMessageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPostMessageCompleted);
            }
            base.InvokeAsync(this.onBeginPostMessageDelegate, new object[] {
                        userName}, this.onEndPostMessageDelegate, this.onPostMessageCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Tungnt.NET.WP8._1Silverlight.WCFDemo.IWCFRestDemo CreateChannel() {
            return new WCFRestDemoClientChannel(this);
        }
        
        private class WCFRestDemoClientChannel : ChannelBase<Tungnt.NET.WP8._1Silverlight.WCFDemo.IWCFRestDemo>, Tungnt.NET.WP8._1Silverlight.WCFDemo.IWCFRestDemo {
            
            public WCFRestDemoClientChannel(System.ServiceModel.ClientBase<Tungnt.NET.WP8._1Silverlight.WCFDemo.IWCFRestDemo> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetMessage(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetMessage", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetMessage(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetMessage", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginPostMessage(string userName, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = userName;
                System.IAsyncResult _result = base.BeginInvoke("PostMessage", _args, callback, asyncState);
                return _result;
            }
            
            public string EndPostMessage(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("PostMessage", _args, result)));
                return _result;
            }
        }
    }
}
